User registration endpoint & database
GenerateNU/voxeti pull request #10
Opened 2023-10-11 03:51 UTC by natesawant

# Description

[Link to Ticket](https://github.com/orgs/GenerateNU/projects/21?pane=issue&itemId=40297137)

1. **GET** _api/users/:id_
2. **GET** _api/users_
3. **POST** _api/users_
4. **PUT** _api/users/:id_
5. **PATCH** _api/users/:id_
6. **DELETE** _api/users/:id_

Includes input validation, email duplication prevention, database idempotency, and coordinate updates

# How Has This Been Tested?

To be implemented

# Checklist

- [X] I have performed a self-review of my code
- [X] I have reached out to another developer to review my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] New and existing unit tests pass locally with my changes

2023-10-11 15:03 UTC, garrettladley reviewed
looks good so far, just some minor nitpicks. also remember to merge main into your branch since there has been some PRs merged recently. Good stuff @natesawant @AaronKim218 😁

2023-10-12 13:38 UTC, garrettladley approved these changes
LGTM ! Great work guys👏

2023-10-12 16:47 UTC, garrettladley approved these changes

2023-10-12 18:53 UTC, jtrrll requested changes
Beautiful work on the backend! Need to make sure the frontend on your branch is either up to date with main or not included in PR, looks like yours is from a few commits back

2023-10-14 19:31 UTC, jtrrll approved these changes

2023-10-14 19:32 UTC, merged